# Generated by Django 5.2 on 2025-06-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tresorerie', '0002_caisse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caisse',
            name='type',
        ),
        migrations.AddField(
            model_name='caisse',
            name='type_operation',
            field=models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie')], default='Versement', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caisse',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='motif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='somme',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='total_grande_caisse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='total_petite_caisse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caisse',
            name='type_caisse',
            field=models.CharField(choices=[('Grande Caisse', 'Grande Caisse'), ('Petite Caisse', 'Petite Caisse')], max_length=20),
        ),
    ]
